language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

dist: trusty

sudo: required

before_script:
  - yarn global add @angular/cli

script:
  - ng lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/datepicker-demo
  on:
    branch: master
